// For user layout
export { default as FlightCard } from './FlightCard'
export { default as HomeNavigation } from './HomeNavigation'
export { default as NavLink } from './NavLink'
export { default as Table } from './Table'
export { default as Select } from './Select'
export { default as LoadingAnimation } from './LoadingAnimation'
export { default as FlightListBanner } from './FlightListBanner'
export { default as Navbar } from './Navbar'
export { default as NavLinkDropDown } from './NavLinkDropDown'
export { default as ButtonOfPage } from './ButtonOfPage'
export { default as FlightListFilter } from './FlightListFilter'
export { default as FlightSearch } from './FlightSearch'
export { default as LoginBanner } from './LoginBanner'
export { default as LangSelect } from './LangSelect'
export { default as SelectDropDown } from './SelectDropDown'
export { default as FooterOfPage } from './FooterOfPage'
export { default as NotFoundFlight } from './NotFoundFlight'
export { default as PageLoadingAnimation } from './PageLoadingAnimation'
export { default as ScrollToTopButton } from './ScrollToTopButton'
export { default as MainLogo } from './MainLogo'
export { default as SmokeAnimation } from './SmokeAnimation'
export { default as FlightDetailModal } from './FlightDetailModal'

//For admin
export { default as AdminSidebar } from './AdminSidebar'
export { default as AdminHeader } from './AdminHeader'
//For User
export { default as UserProfileSidebar } from './UserProfileSidebar'
export { default as UserTicket } from './UserTicket'
export { default as UserBookingDetail } from './UserBookingDetail'
export { default as UserBookingTable } from './UserBookingTable'
